const imgUrl = `${process.env.PUBLIC_URL}/assets/images/Mypage/wish/`;

export const MypageWishData = [
  {
    id: 0,
    name: "레드 플라워 원피스",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "S",
    state: "좋음",
    price: "19000",
    wish_state: "판매중",
    url: `${imgUrl}wish0.png`,
  },
  {
    id: 1,
    name: "니트 크롭탑",
    brand: "Realization Par",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "XS",
    state: "보통",
    price: "9000",
    wish_state: "판매완료",
    url: `${imgUrl}wish1.png`,
  },
  {
    id: 2,
    name: "디스트로이드 청 반바지",
    brand: "New Balance",
    hashtag: "#뉴발란스 #운동화 #데일리템 #러닝화 ",
    size: "26",
    state: "매우좋음",
    price: "30000",
    wish_state: "판매중",
    url: `${imgUrl}wish2.png`,
  },
  {
    id: 3,
    name: "베이지 자켓",
    brand: "Champion",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "L",
    state: "좋음",
    price: "25000",
    wish_state: "판매중",
    url: `${imgUrl}wish3.png`,
  },
  {
    id: 4,
    name: "호피 슬릿 스커트",
    brand: "None",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "S",
    state: "보통",
    price: "12000",
    wish_state: "판매중",
    url: `${imgUrl}wish4.png`,
  },
  {
    id: 5,
    name: "옐로우 퍼 파우치",
    brand: "Zara",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "S",
    state: "좋음",
    price: "19000",
    wish_state: "판매중",
    url: `${imgUrl}wish5.png`,
  },
  {
    id: 6,
    name: "캐러멜 블루종",
    brand: "COS",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "L",
    state: "매우좋음",
    price: "198000",
    wish_state: "판매중",
    url: `${imgUrl}wish6.png`,
  },
];
