const imgUrl = `${process.env.PUBLIC_URL}/assets/images/Mypage/sale/`;

export const MypageSaleData = [
  {
    id: 0,
    name: "네온패턴 부츠컷 팬츠",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 #Y2K",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    saleYMD: "2022.10.19",
    url: `${imgUrl}sale0.png`,
  },
  {
    id: 1,
    name: "니트 크롭탑",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 #Y2K",
    size: "XS",
    state: "보통",
    likes: "10",
    price: "9000",
    saleYMD: "2022.10.19",
    url: `${imgUrl}sale1.png`,
  },
  {
    id: 2,
    name: "뉴발란스 N392",
    brand: "New Balance",
    hashtag: "#N392 #뉴발란스 #운동화 #데일리템 #러닝화",
    size: "245",
    state: "매우좋음",
    likes: "15",
    price: "30000",
    saleYMD: "2022.10.19",
    url: `${imgUrl}sale2.png`,
  },
  {
    id: 3,
    name: "셰도우 조거팬츠",
    brand: "Champion",
    hashtag: "#원마일웨이룩 #조거팬츠 #트레이닝팬츠 #챔피온",
    size: "L",
    state: "좋음",
    likes: "2",
    price: "25000",
    saleYMD: "2022.10.19",
    url: `${imgUrl}sale3.png`,
  },
  {
    id: 4,
    name: "차콜 카고팬츠",
    brand: "None",
    hashtag: "#데일리템 #바지 #카고팬츠 #와이드팬츠 #Y2K",
    size: "S",
    state: "보통",
    likes: "8",
    price: "12000",
    saleYMD: "2022.10.19",
    url: `${imgUrl}sale4.png`,
  },
  {
    id: 5,
    name: "베이지 자켓",
    brand: "Champion",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "L",
    state: "좋음",
    likes: "3",
    price: "69000",
    saleYMD: "2022.09.30",
    url: `${imgUrl}wish3.png`,
  },
  {
    id: 6,
    name: "호피 슬릿 스커트",
    brand: "None",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 # Y2K",
    size: "S",
    state: "보통",
    likes: "3",
    price: "14000",
    saleYMD: "2022.09.30",
    url: `${imgUrl}wish4.png`,
  },
];
