const imgUrl = `${process.env.PUBLIC_URL}/assets/images/Mypage/sale/`;

export const MypageSaleData = [
  {
    id: 0,
    name: "네온패턴 부츠컷 팬츠",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 #Y2K",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}sale0.png`,
  },
  {
    id: 1,
    name: "니트 크롭탑",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷 #네온 #유니크 #Y2K",
    size: "XS",
    state: "보통",
    likes: "10",
    price: "9000",
    url: `${imgUrl}sale1.png`,
  },
  {
    id: 2,
    name: "뉴발란스 N392",
    brand: "New Balance",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "보통",
    likes: "3",
    price: "339000",
    url: `${imgUrl}sale2.png`,
  },
  {
    id: 3,
    name: "네온패턴 부츠컷 팬츠4",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "49000",
    url: `${imgUrl}sale3.png`,
  },
  {
    id: 4,
    name: "네온패턴 부츠컷 팬츠5",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "59000",
    url: `${imgUrl}sale4.png`,
  },
  {
    id: 5,
    name: "네온패턴 부츠컷 팬츠6",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "69000",
    url: `${imgUrl}sale4.png`,
  },
  {
    id: 6,
    name: "네온패턴 부츠컷 팬츠7",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "79000",
    url: `${imgUrl}sale4.png`,
  },
  {
    id: 7,
    name: "네온패턴 부츠컷 팬츠8",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}sale4.png`,
  },
  {
    id: 8,
    name: "네온패턴 부츠컷 팬츠9",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}sale4.png`,
  },
];
