const imgUrl = `${process.env.PUBLIC_URL}/assets/images/NewItemSection/`;

export const MypageSaleData = [
  {
    id: 0,
    name: "네온패턴 부츠컷 부츠컷 부츠컷 ",
    brand: "The Open Produasdfsfsafct",
    hashtag: "#비비드 #부츠컷 #부츠컷 #부츠컷 #부츠컷 #부츠컷 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 1,
    name: "네온패턴 부츠컷 팬츠2",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "매우 좋음",
    likes: "3",
    price: "129000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 2,
    name: "네온패턴 부츠컷 팬츠3",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "보통",
    likes: "3",
    price: "339000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 3,
    name: "네온패턴 부츠컷 팬츠4",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "49000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 4,
    name: "네온패턴 부츠컷 팬츠5",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "59000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 5,
    name: "네온패턴 부츠컷 팬츠6",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "69000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 6,
    name: "네온패턴 부츠컷 팬츠7",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "79000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 7,
    name: "네온패턴 부츠컷 팬츠8",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}newitem.jpg`,
  },
  {
    id: 8,
    name: "네온패턴 부츠컷 팬츠9",
    brand: "The Open Product",
    hashtag: "#비비드 #부츠컷",
    size: "S",
    state: "좋음",
    likes: "3",
    price: "19000",
    url: `${imgUrl}newitem.jpg`,
  },
];
