const filterImgUrl = `${process.env.PUBLIC_URL}/assets/images/filterImg/`;

export const newFilterData = [
  {
    id: 1,
    like_num: 15,
    size: "F",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}1.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 2,
    like_num: 15,
    size: "L",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}2.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 3,
    like_num: 15,
    size: "M",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}3.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 4,
    like_num: 15,
    size: "XL",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}4.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 5,
    like_num: 15,
    size: "XS",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}5.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 6,
    like_num: 15,
    size: "8",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}4.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 7,
    like_num: 15,
    size: "F",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}3.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 8,
    like_num: 15,
    size: "XS",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}2.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 9,
    like_num: 15,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}1.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 10,
    like_num: 15,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}2.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 11,
    like_num: 15,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "레오파드 맥시스커트",
    product_img_url: `${filterImgUrl}3.png`,
    price: 15000,
    inCart: false,
  },
];
