const filterImgUrl = `${process.env.PUBLIC_URL}/assets/images/newCollectionImg/`;

export const newFilterData = [
  {
    id: 1,
    like_num: 15,
    size: "XS",
    isLike: false,
    brand: "ZARA",
    name: "그레이 크롭 나시",
    product_img_url: `${filterImgUrl}sl_newitem1.png`,
    price: 6000,
    inCart: false,
  },
  {
    id: 2,
    like_num: 6,
    size: "M",
    isLike: false,
    brand: "SPO",
    name: "스카이 조거 트레이닝",
    product_img_url: `${filterImgUrl}sl_newitem2.png`,
    price: 12000,
    inCart: false,
  },
  {
    id: 3,
    like_num: 5,
    size: "L",
    isLike: false,
    brand: "ZARA",
    name: "자수 플라워 긴팔 원피스",
    product_img_url: `${filterImgUrl}sl_newitem3.png`,
    price: 9000,
    inCart: false,
  },
  {
    id: 4,
    like_num: 1,
    size: "S",
    isLike: false,
    brand: "Bershka",
    name: "핑크 형광 스포츠 반바지",
    product_img_url: `${filterImgUrl}sl_newitem4.png`,
    price: 5000,
    inCart: false,
  },
  {
    id: 5,
    like_num: 20,
    size: "28",
    isLike: false,
    brand: "H&M",
    name: "와이드 팬츠 플라워 패턴",
    product_img_url: `${filterImgUrl}sl_newitem5.png`,
    price: 28000,
    inCart: false,
  },
  {
    id: 6,
    like_num: 12,
    size: "S",
    isLike: false,
    brand: "MIXXO",
    name: "크롭 단추 베이지 나시",
    product_img_url: `${filterImgUrl}sl_newitem6.png`,
    price: 7000,
    inCart: false,
  },
  {
    id: 7,
    like_num: 14,
    size: "M",
    isLike: false,
    brand: "H&M",
    name: "워싱 청 반바지",
    product_img_url: `${filterImgUrl}sl_newitem7.png`,
    price: 12000,
    inCart: false,
  },
  {
    id: 8,
    like_num: 16,
    size: "245",
    isLike: false,
    brand: "New Balance",
    name: "뉴발란스 블랙 245",
    product_img_url: `${filterImgUrl}sl_newitem8.png`,
    price: 35000,
    inCart: false,
  },
  {
    id: 9,
    like_num: 0,
    size: "M",
    isLike: false,
    brand: "ZARA",
    name: "레인보우 롱팬츠",
    product_img_url: `${filterImgUrl}sl_newitem9.png`,
    price: 23000,
    inCart: false,
  },
  {
    id: 10,
    like_num: 5,
    size: "S",
    isLike: false,
    brand: "ZARA",
    name: "라임 브이넥 반팔 티셔츠",
    product_img_url: `${filterImgUrl}sl_newitem10.png`,
    price: 4000,
    inCart: false,
  },
  {
    id: 11,
    like_num: 6,
    size: "M",
    isLike: false,
    brand: "8IGHT SECONDS",
    name: "화이트 브이넥 집업",
    product_img_url: `${filterImgUrl}sl_newitem11.png`,
    price: 13500,
    inCart: false,
  },
  {
    id: 12,
    like_num: 2,
    size: "L",
    isLike: false,
    brand: "GAP",
    name: "다크 그레이 후드",
    product_img_url: `${filterImgUrl}sl_newitem12.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 13,
    like_num: 13,
    size: "26",
    isLike: false,
    brand: "TOP TEN",
    name: "그레이 카고 팬츠 ",
    product_img_url: `${filterImgUrl}sl_newitem13.png`,
    price: 23000,
    inCart: false,
  },
  {
    id: 14,
    like_num: 4,
    size: "M",
    isLike: false,
    brand: "TOP TEN",
    name: "레터링 화이트 조거팬츠",
    product_img_url: `${filterImgUrl}sl_newitem14.png`,
    price: 20000,
    inCart: false,
  },
  {
    id: 15,
    like_num: 6,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "크롭 니트 나시 크림색",
    product_img_url: `${filterImgUrl}sl_newitem15.png`,
    price: 12000,
    inCart: false,
  },
  {
    id: 16,
    like_num: 7,
    size: "M",
    isLike: false,
    brand: "ZARA",
    name: "스퀘어넥 반팔 퍼프 티셔츠",
    product_img_url: `${filterImgUrl}sl_newitem16.png`,
    price: 8000,
    inCart: false,
  },
  {
    id: 17,
    like_num: 8,
    size: "M",
    isLike: false,
    brand: "ZARA",
    name: "스카이 시스루 긴팔 셔츠",
    product_img_url: `${filterImgUrl}sl_newitem17.png`,
    price: 32000,
    inCart: false,
  },
  {
    id: 18,
    like_num: 8,
    size: "26",
    isLike: false,
    brand: "MIXXO",
    name: "핀턱 베이지 팬츠",
    product_img_url: `${filterImgUrl}sl_newitem18.png`,
    price: 23000,
    inCart: false,
  },
  {
    id: 19,
    like_num: 9,
    size: "XS",
    isLike: false,
    brand: "ZARA",
    name: "코튼 튜브탑 ",
    product_img_url: `${filterImgUrl}sl_newitem19.png`,
    price: 2000,
    inCart: false,
  },
  {
    id: 20,
    like_num: 2,
    size: "M",
    isLike: false,
    brand: "MIXXO",
    name: "반달 크로스 백",
    product_img_url: `${filterImgUrl}sl_newitem20.png`,
    price: 13000,
    inCart: false,
  },
];
