const filterImgUrl = `${process.env.PUBLIC_URL}/assets/images/popularImg/`;

export const popularFilterData = [
  {
    id: 1,
    like_num: 15,
    size: "F",
    isLike: false,
    brand: "-",
    name: "레드립 탱크탑",
    product_img_url: `${filterImgUrl}popularitem1.png`,
    price: 7000,
    inCart: false,
  },
  {
    id: 200,
    like_num: 20,
    size: "250",
    isLike: false,
    brand: "NEW BALANCE",
    name: "뉴발란스 화이트 슈즈",
    product_img_url: `${filterImgUrl}popularitem2.png`,
    price: 41000,
    inCart: false,
  },
  {
    id: 3,
    like_num: 17,
    size: "S",
    isLike: false,
    brand: "ZARA",
    name: "딥브이넥 탑 ",
    product_img_url: `${filterImgUrl}popularitem3.png`,
    price: 13000,
    inCart: false,
  },
  {
    id: 4,
    like_num: 27,
    size: "26",
    isLike: false,
    brand: "H&M",
    name: "스트라이프 부츠컷 팬츠",
    product_img_url: `${filterImgUrl}popularitem4.png`,
    price: 7000,
    inCart: false,
  },
  {
    id: 5,
    like_num: 15,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "롱슬리브리스 퍼프 셔츠",
    product_img_url: `${filterImgUrl}popularitem5.png`,
    price: 23000,
    inCart: false,
  },
  {
    id: 6,
    like_num: 16,
    size: "M",
    isLike: false,
    brand: "-",
    name: "와이드 연청 진",
    product_img_url: `${filterImgUrl}popularitem6.png`,
    price: 17000,
    inCart: false,
  },
  {
    id: 7,
    like_num: 18,
    size: "M",
    isLike: false,
    brand: "MIXXO",
    name: "호피 롱 스커트",
    product_img_url: `${filterImgUrl}popularitem7.png`,
    price: 13000,
    inCart: false,
  },
  {
    id: 8,
    like_num: 29,
    size: "24",
    isLike: false,
    brand: "ZARA",
    name: "스키니 블랙 진",
    product_img_url: `${filterImgUrl}popularitem8.png`,
    price: 9000,
    inCart: false,
  },
  {
    id: 9,
    like_num: 31,
    size: "26",
    isLike: false,
    brand: "ZARA",
    name: "디스트로이드 연청 숏츠",
    product_img_url: `${filterImgUrl}popularitem9.png`,
    price: 11000,
    inCart: false,
  },
  {
    id: 10,
    like_num: 28,
    size: "L",
    isLike: false,
    brand: "H&M",
    name: "핸리 브이넥 원피스",
    product_img_url: `${filterImgUrl}popularitem10.png`,
    price: 20000,
    inCart: false,
  },
  {
    id: 11,
    like_num: 19,
    size: "F",
    isLike: false,
    brand: "-",
    name: "하트 포인트 블랙 나시",
    product_img_url: `${filterImgUrl}popularitem11.png`,
    price: 6000,
    inCart: false,
  },
  {
    id: 12,
    like_num: 17,
    size: "L",
    isLike: false,
    brand: "UNIQLO",
    name: "브릭 블루종",
    product_img_url: `${filterImgUrl}popularitem12.png`,
    price: 30000,
    inCart: false,
  },
  {
    id: 13,
    like_num: 25,
    size: "245",
    isLike: false,
    brand: "NIKE",
    name: "그레이 나이키 에어 ",
    product_img_url: `${filterImgUrl}popularitem13.png`,
    price: 51000,
    inCart: false,
  },
  {
    id: 14,
    like_num: 38,
    size: "L",
    isLike: false,
    brand: "ZARA",
    name: "라탄 원형 백",
    product_img_url: `${filterImgUrl}popularitem14.png`,
    price: 30000,
    inCart: false,
  },
  {
    id: 15,
    like_num: 25,
    size: "S",
    isLike: false,
    brand: "-",
    name: "화이트 크롭 나시",
    product_img_url: `${filterImgUrl}popularitem15.png`,
    price: 10000,
    inCart: false,
  },
  {
    id: 16,
    like_num: 16,
    size: "M",
    isLike: false,
    brand: "SPAO",
    name: "숏 청자켓",
    product_img_url: `${filterImgUrl}popularitem16.png`,
    price: 17000,
    inCart: false,
  },
  {
    id: 17,
    like_num: 18,
    size: "M",
    isLike: false,
    brand: "-",
    name: "스퀘어 레드 숄더백",
    product_img_url: `${filterImgUrl}popularitem17.png`,
    price: 6000,
    inCart: false,
  },
];
