const newImgUrl = `${process.env.PUBLIC_URL}/assets/images/newCollectionImg/`;
const popularImgUrl = `${process.env.PUBLIC_URL}/assets/images/popularImg/`;

export const topItemsData = [
  {
    id: 100,
    like_num: 15,
    size: "XS",
    isLike: false,
    brand: "ZARA",
    name: "그레이 크롭 나시",
    product_img_url: `${newImgUrl}sl_newitem1.png`,
    price: 6000,
    inCart: false,
  },
  {
    id: 2,
    like_num: 12,
    size: "S",
    isLike: false,
    brand: "MIXXO",
    name: "크롭 단추 베이지 나시",
    product_img_url: `${newImgUrl}sl_newitem6.png`,
    price: 7000,
    inCart: false,
  },
  {
    id: 3,
    like_num: 5,
    size: "S",
    isLike: false,
    brand: "ZARA",
    name: "라임 브이넥 반팔 티셔츠",
    product_img_url: `${newImgUrl}sl_newitem10.png`,
    price: 4000,
    inCart: false,
  },
  {
    id: 4,
    like_num: 2,
    size: "L",
    isLike: false,
    brand: "GAP",
    name: "다크 그레이 후드",
    product_img_url: `${newImgUrl}sl_newitem12.png`,
    price: 15000,
    inCart: false,
  },
  {
    id: 5,
    like_num: 6,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "크롭 니트 나시 크림색",
    product_img_url: `${newImgUrl}sl_newitem15.png`,
    price: 12000,
    inCart: false,
  },
  {
    id: 6,
    like_num: 7,
    size: "M",
    isLike: false,
    brand: "ZARA",
    name: "스퀘어넥 반팔 퍼프 티셔츠",
    product_img_url: `${newImgUrl}sl_newitem16.png`,
    price: 8000,
    inCart: false,
  },
  {
    id: 7,
    like_num: 8,
    size: "M",
    isLike: false,
    brand: "ZARA",
    name: "스카이 시스루 긴팔 셔츠",
    product_img_url: `${newImgUrl}sl_newitem17.png`,
    price: 32000,
    inCart: false,
  },
  {
    id: 8,
    like_num: 9,
    size: "XS",
    isLike: false,
    brand: "ZARA",
    name: "코튼 튜브탑 ",
    product_img_url: `${newImgUrl}sl_newitem19.png`,
    price: 2000,
    inCart: false,
  },
  {
    id: 9,
    like_num: 15,
    size: "F",
    isLike: false,
    brand: "-",
    name: "레드립 탱크탑",
    product_img_url: `${popularImgUrl}popularitem1.png`,
    price: 7000,
    inCart: false,
  },
  {
    id: 103,
    like_num: 17,
    size: "S",
    isLike: false,
    brand: "ZARA",
    name: "딥브이넥 탑 ",
    product_img_url: `${popularImgUrl}popularitem3.png`,
    price: 13000,
    inCart: false,
  },
  {
    id: 11,
    like_num: 15,
    size: "S",
    isLike: false,
    brand: "H&M",
    name: "롱슬리브리스 퍼프 셔츠",
    product_img_url: `${popularImgUrl}popularitem5.png`,
    price: 23000,
    inCart: false,
  },
  {
    id: 12,
    like_num: 19,
    size: "F",
    isLike: false,
    brand: "-",
    name: "하트 포인트 블랙 나시",
    product_img_url: `${popularImgUrl}popularitem11.png`,
    price: 6000,
    inCart: false,
  },
  {
    id: 13,
    like_num: 25,
    size: "S",
    isLike: false,
    brand: "-",
    name: "화이트 크롭 나시",
    product_img_url: `${popularImgUrl}popularitem15.png`,
    price: 10000,
    inCart: false,
  },
];
