const imgUrl = `${process.env.PUBLIC_URL}/assets/images/`;

export const TopSellerSectiondata = [
  {
    no: 0,
    UserId: "aaa1",
    HashTag: "#모자 #티셔츠1",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 100,
    sold: 50,
  },
  {
    no: 1,
    UserId: "aaa2",
    HashTag: "#모자 #티셔츠2",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 101,
    sold: 51,
  },
  {
    no: 2,
    UserId: "aaa3",
    HashTag: "#모자 #티셔츠3",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 102,
    sold: 52,
  },
  {
    no: 3,
    UserId: "aaa4",
    HashTag: "#모자 #티셔츠4",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 103,
    sold: 53,
  },
  {
    no: 4,
    UserId: "aaa5",
    HashTag: "#모자 #점프슈트",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 104,
    sold: 54,
  },
  {
    no: 5,
    UserId: "aaa6",
    HashTag: "#모자 #긴팔티셔츠",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 105,
    sold: 55,
  },
  {
    no: 6,
    UserId: "aaa7",
    HashTag: "#모자 #드레스",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 106,
    sold: 56,
  },
  {
    no: 7,
    UserId: "aaa8",
    HashTag: "#모자 #장갑",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 107,
    sold: 57,
  },
  {
    no: 8,
    UserId: "aaa9",
    HashTag: "#모자 #양말",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 108,
    sold: 58,
  },
  {
    no: 9,
    UserId: "aaa10",
    HashTag: "#모자 #운동화",
    url: `${imgUrl}TopSeller.jpg`,
    followers: 109,
    sold: 59,
  },
];
